before_script:
  - export GOPATH=$(pwd)

stages:
  - build
  - test
  - deploy

compile-go-1.5:
  image: golang:1.5
  stage: build
  script:
    - git submodule update --init
    - make get_deps
    - make get_dev_deps
    - make