language: go

sudo: false

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: never
    on_failure: always

go:
  - 1.6.3
  - 1.7.1

install:
  - go get github.com/mattn/goveralls
  - curl https://glide.sh/get | sh
  - make get

script:
  - make
  - make test

after_success:
  - make coverage
  - goveralls -coverprofile=coverage.out -service=travis-ci
