language: go

sudo: false

branches:
  only:
    - master
    - develop

go:
  - 1.5.4
  - 1.6.3
  - 1.7

script:
  - $HOME/gopath/bin/goveralls

install:
  - go get github.com/mattn/goveralls
  - go get -t ./...

script:
  - make
  - make test

after_success:
  - make coverage
  - goveralls -coverprofile=coverage.out -service=travis-ci
